# Generated by Django 5.1 on 2025-05-14 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('symbol', models.CharField(help_text='Stock symbol e.g. AAPL', max_length=20)),
                ('condition_type', models.CharField(choices=[('price_above', 'Price Above Threshold'), ('price_below', 'Price Below Threshold'), ('price_up_percent', 'Price Up by Percentage'), ('price_down_percent', 'Price Down by Percentage'), ('volume_spike', 'Volume Spike'), ('rsi_overbought', 'RSI Overbought (>70)'), ('rsi_oversold', 'RSI Oversold (<30)'), ('custom', 'Custom Condition')], max_length=50)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('custom_condition', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('one_time', 'One Time'), ('repeating', 'Repeating'), ('continuous', 'Continuous')], default='one_time', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('triggered', 'Triggered'), ('completed', 'Completed'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('times_triggered', models.PositiveIntegerField(default=0)),
                ('portfolio_id', models.UUIDField(blank=True, null=True)),
                ('stock_id', models.UUIDField(blank=True, null=True)),
                ('email_notification', models.BooleanField(default=True)),
                ('sound_notification', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
