# Generated by Django 5.1 on 2025-05-17 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0001_initial'),
        ('portfolios', '0007_alter_investment_adv_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='portfolio_id',
        ),
        migrations.AddField(
            model_name='alert',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='portfolios.portfolio'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='condition_type',
            field=models.CharField(choices=[('price_above', 'Price Above Threshold'), ('price_below', 'Price Below Threshold'), ('price_up_percent', 'Price Up by Percentage'), ('price_down_percent', 'Price Down by Percentage'), ('volume_spike', 'Volume Spike'), ('rsi_overbought', 'RSI Overbought'), ('rsi_oversold', 'RSI Oversold'), ('custom', 'Custom Condition')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='custom_condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='stock_id',
            field=models.CharField(blank=True, help_text='ID of stock transaction in portfolio', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='threshold_value',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='times_triggered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alert',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
