# Generated by Django 5.1 on 2024-09-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("risk_management", "0005_remove_riskprofile_stocks"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskprofile",
            name="period_return_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="riskprofile",
            name="period_return_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
