# Generated by Django 5.1 on 2025-03-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psxscreener', '0002_stock_stockscreener_stockwatchlist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-date', 'symbol']},
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['symbol', 'sector'], name='psxscreener_symbol_eca2a2_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['date', 'sector'], name='psxscreener_date_38afc4_idx'),
        ),
    ]
