# Generated by Django 5.1 on 2025-03-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psxscreener', '0003_alter_stock_options_alter_stock_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
