# Generated by Django 5.1 on 2025-05-17 09:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('price_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_change_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume', models.BigIntegerField()),
                ('risk_rating', models.CharField(choices=[('LOW', 'Low Risk'), ('MODERATE', 'Moderate Risk'), ('HIGH', 'High Risk')], max_length=10)),
                ('quantra_rating', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Good'), ('C', 'C - Average'), ('D', 'D - Below Average'), ('E', 'E - Poor')], max_length=1)),
                ('overview', models.TextField()),
                ('founded_year', models.IntegerField()),
                ('ceo', models.CharField(max_length=255)),
                ('headquarters', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekly_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('three_month_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('six_month_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yearly_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ytd_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='Fullview.stock')),
            ],
        ),
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('DIVIDEND', 'Dividend'), ('SPLIT', 'Stock Split'), ('MERGER', 'Merger'), ('ACQUISITION', 'Acquisition'), ('OTHER', 'Other')], max_length=20)),
                ('announcement_date', models.DateField()),
                ('effective_date', models.DateField()),
                ('description', models.TextField()),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_actions', to='Fullview.stock')),
            ],
            options={
                'ordering': ['-announcement_date'],
            },
        ),
        migrations.CreateModel(
            name='CompanySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative')], max_length=10)),
                ('headline', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('source_url', models.URLField(blank=True)),
                ('published_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='Fullview.stock')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundamental_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('technical_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sentiment_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('valuation_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('dividend_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('outlook_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='Fullview.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stocks', models.ManyToManyField(related_name='watchlists', to='Fullview.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
