# Generated by Django 5.1 on 2025-05-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fullview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysignal',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='corporateaction',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='stocks',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='CompanyAnalysis',
        ),
        migrations.DeleteModel(
            name='CompanySignal',
        ),
        migrations.DeleteModel(
            name='CorporateAction',
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
