# Generated by Django 5.1 on 2025-04-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volume', models.BigIntegerField()),
                ('pe_ratio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('prev_close', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('change', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol'], name='SmartScreen_symbol_337764_idx'), models.Index(fields=['sector'], name='SmartScreen_sector_ac05b5_idx'), models.Index(fields=['industry'], name='SmartScreen_industr_026ca1_idx')],
            },
        ),
    ]
