# Generated by Django 5.0.7 on 2024-08-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
