# Generated by Django 5.1 on 2024-09-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0004_rate_ldcp_rate_pct_change_stock_metadata_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="is_kse100",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="is_kse30",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="is_kse50",
        ),
        migrations.AddField(
            model_name="stock",
            name="index",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "KSE100"),
                    ("2", "ALLSHR"),
                    ("3", "KSE30"),
                    ("4", "KMI30"),
                    ("5", "KMIALLSHR"),
                    ("6", "BKTI"),
                    ("7", "OGTI"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
