# Generated by Django 5.1 on 2024-09-23 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0006_alter_stock_index"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stock",
            options={
                "ordering": ["ticker"],
                "verbose_name": "Stock",
                "verbose_name_plural": "Stocks",
            },
        ),
    ]
