# Generated by Django 5.1 on 2024-09-24 09:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_remove_stock_metadata_alter_stock_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='index',
        ),
        migrations.AddField(
            model_name='stock',
            name='indices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(1, 'KSE100'), (2, 'KSE_ALLSHR'), (3, 'KSE30'), (4, 'KMI30'), (5, 'KMI_ALLSHR'), (6, 'BKTI'), (7, 'OGTI')], default=2), default=list, size=None),
        ),
    ]
