# Generated by Django 5.1 on 2024-09-25 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_alter_stock_indices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
