# Generated by Django 5.0.7 on 2024-08-06 19:07

import apps.portfolios.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="investment",
            options={
                "ordering": ["-added_at", "-transaction_date"],
                "verbose_name": "Investment",
                "verbose_name_plural": "Investments",
            },
        ),
        migrations.RemoveField(
            model_name="investment",
            name="date",
        ),
        migrations.RemoveField(
            model_name="investment",
            name="psx_laga",
        ),
        migrations.RemoveField(
            model_name="investment",
            name="secp_laga",
        ),
        migrations.RemoveField(
            model_name="investment",
            name="wht",
        ),
        migrations.AddField(
            model_name="investment",
            name="bill",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="investment",
            name="book",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="investment",
            name="cdc_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="investment",
            name="client",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="investment",
            name="client_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="investment",
            name="client_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="investment",
            name="cot_st",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="investment",
            name="dealer",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="investment",
            name="fed",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="flag",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="investment",
            name="korder",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="investment",
            name="laga",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="investment",
            name="misc",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="nlaga",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="occupation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="investment",
            name="psx",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="residence",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="investment",
            name="secp",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="settlement_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="investment",
            name="terminal",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="investment",
            name="ticket",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="investment",
            name="transaction_date",
            field=models.DateField(
                null=True, validators=[apps.portfolios.models.validate_not_in_future]
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="transaction_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="investment",
            name="whtc",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="whts",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="brokerage_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=15.0, max_digits=4, null=True
            ),
        ),
    ]
