# Generated by Django 5.1 on 2024-09-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolios", "0003_portfolio_dividends_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="dividends",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=14
            ),
        ),
    ]
