# Generated by Django 5.1 on 2024-10-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_alter_portfolio_dividends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
