# Generated by Django 5.1 on 2025-03-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_alter_investment_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
