# Generated by Django 5.1 on 2025-03-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_alter_investment_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='adv_tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='brokerage_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='investment',
            name='cdc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='cvt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='fed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='laga',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='misc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='nccpl',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='nlaga',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='psx',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='investment',
            name='secp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='sst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='whtc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='whts',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
    ]
